# Copyright (c) 2022 The Bitcoin developers

[workspace]

members = [
    "chronik/abc-rust-error",
    "chronik/abc-rust-lint",
    "chronik/bitcoinsuite-core",
    "chronik/chronik-bridge",
    "chronik/chronik-db",
    "chronik/chronik-lib",
]
