[package]
name = "bitcoinsuite-slp"
version = "0.1.0"
authors = ["Tobias Ruck <ruck.tobias@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Base crate
bitcoinsuite-core = { path = "../bitcoinsuite-core" }

# Error handling 
thiserror = "1.0"
bitcoinsuite-error = { path = "../bitcoinsuite-error" }

async-trait = "0.1.50"
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.0"
