[package]
name = "chronik-bitcoind-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
chronik-interface = { path = "../chronik-interface" }

json = "0.12"
hex = "0.4"

# Error handling
thiserror = "1.0"
bitcoinsuite-error = { path = "../../bitcoinsuite/bitcoinsuite-error" }
